### ISSUE TITLE
Possible Optimization

### ISSUE THREAD

**Issue by kaminary** [clbr/urlmatch#2]
Here you calculate the length of the pattern: https://github.com/clbr/urlmatch/blob/master/simple.c#L30
What if the pattern has a bigger length than the url beign matched?
Ex: 
Pattern: http\* ://\* .asite.com/someResource/**
Url: https://www.asite.com/
In this case I think the comparison can be speed up if you just test the size of the pattern and the url to be matched.

I think the pattern size cannot never be bigger than the url size. So this can cut off some checks.
I cannot think a pattern that will be bigger than the url to be matched and still match.
So a possible optimization will be check if the size of the pattern is at least 10% bigger than the url beign matched. If it is you can skip and assume that it will not match.

What do you think?

**Comment by clbr** [comment]
> I think the pattern size cannot never be bigger than the url size. So this can cut off some checks.
> I cannot think a pattern that will be bigger than the url to be matched and still match.
> So a possible optimization will be check if the size of the pattern is at least 10% bigger than the url beign matched. If it is you can skip and assume that it will not match.

The star \* can match zero, so it's quite possible the pattern is larger
and still matches:

url: http://company.com
pattern: _http://company.com_
pattern: http://co_m_p_a_ny.com*

The other thing is that you're looking at the simple matcher, which is
not used for actual work, and mainly included for benchmark purposes.
Some optimizations to it will apply to the optimized matcher of course.

**Comment by kaminary** [comment]
Yeah, you're right.
I will close the issue.
