### ISSUE TITLE
Undefined Behavior on URL match

### ISSUE THREAD

**Issue by kaminary** [clbr/urlmatch#3]
Reading your source I found a possible undefined behavior at line [40](https://github.com/clbr/urlmatch/blob/master/simple.c#L40).
You keep incrementing the index without any true control, so if you increment it after the end of the char array then you will hit a memory that is not alocated by your program.

Reading a pointer off the limit is not the problem, but the line [42](https://github.com/clbr/urlmatch/blob/master/simple.c#L42) can be bypassed if for some crazy reason there is an asterisk at that position.
Some lines after [50](https://github.com/clbr/urlmatch/blob/master/simple.c#L50) you copy memory from this supposedly undefined area, and the program can possible crash.

**Comment by clbr** [comment]
Thanks. Can you construct a test case for such? I'd like to add it to
the tests.

**Comment by clbr** [comment]
Actually, I don't think this scenario can happen with any valid string
(NULL-terminated). That's part of the contract, any library accepting C
strings will blow up when passed non-NULL-terminated strings.

pattern "**_" is {_, *, *, 0}. Its length is 3.

The star skip will increment i to 2, which will be caught by the check
at line 42.

**Comment by kaminary** [comment]
Hmm, yes. I have forgotten the end-line terminator `\0`.
I cannot think in a way to pass a non-null terminated string that will bypass all functions and stop at this one, but in any case, I think changing the check at [42](https://github.com/clbr/urlmatch/blob/master/simple.c#L42) to verify if variable **i** is greather or equal the size won't hurt at all.

``` C++
if (i >= len - 1)
return 1;
```
